config/routes.rb
Objectspan::Application.routes.draw do
  
  resources :relationship_types

  resources :user_item_relationships

  resources :company_categorizations

  resources :item_categorizations

  resources :categories

  resources :purchase_item_feedbacks

  resources :purchase_feedbacks

  resources :company_contacts

  resources :company_countries

  resources :company_types

  resources :return_duration_types

  resources :exchange_duration_types

  resources :company_return_policies

  resources :company_category_return_policies

  resources :company_items

  resources :mail_in_rebate_statuses

  resources :purchase_item_statuses

  resources :payment_methods

  resources :duration_frequencies

  resources :purchases 
    resources :purchase_items
  

  resources :return_categories

  resources :purchase_statuses

  resources :stores

  resources :states

  resources :countries

  resources :companies

  resources :groups

  resources :visibilities

  resources :store_types

  resources :items do
    collection { post :search, to: 'items#index' }
  end

  resources :makes
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'tags/:tag', to: 'items#index', as: :tag

  match '/auth/:provider/callback', to: 'sessions#create'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

  match '/product', to: 'static_pages#product'

  match '/contact', to: 'static_pages#contact'

  match '/signup', to: 'users#new'

end

app/models/store.rb
class Store < ActiveRecord::Base
	belongs_to :country
	belongs_to :state
	belongs_to :company
	belongs_to :store_type

	has_many :store_items
	has_many :items, :through => :store_items
	has_many :purchases

	has_attached_file :photo, :styles => { :small => "150x150>", :medium => "300x300>", :thumb => "100x100>" },
							  :url  => "/assets/stores/:id/photos/:style/:basename.:extension",
                  			  :path => ":rails_root/public/assets/stores/:id/photos/:style/:basename.:extension"

  	attr_accessible :photo, :address1, :address2, :city, :company_id, :country_id, :description, :email, 
  	:fax, :latitude, :longitude, :name, :other_state, :phone, :rating, :state_id, :store_number, :store_type_id, 
  	:store_url, :zipcode, :type, :company_name
  	
	validates_attachment_size :photo, :less_than => 5.megabytes
	validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

	def type
		store_type.try(:name)
	end
	
	def type=(name)
		self.store_type = StoreType.find_by_name(name)
	end

	def company_name
		self.company.try(:name)
	end

	def company_name=(name)
		self.company = Company.find_or_create_by_name(name) if name.present?
	end


	def self.all_stores_by_type(name)
		type = StoreType.find_by_name(name)
		Store.find_all_by_store_type_id(type.id)
	end

	def self.all_stores_by_company(name)
		company = Company.find_by_name(name)
		Store.find_all_by_company_id(company.id)
	end

end

app/models/store_type.rb
class StoreType < ActiveRecord::Base
  has_many :stores
  attr_accessible :name

  validates :name, :presence => true, uniqueness: { case_sensitive: false }
  
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.order(:name).where("name like ?", "%#{params[:term]}%")
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stores.map(&:name) }
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @store = Store.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/new
  # GET /stores/new.json
  def new
    @store = Store.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/1/edit
  def edit
    @store = Store.find(params[:id])
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(params[:store])

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render json: @store, status: :created, location: @store }
      else
        format.html { render action: "new" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stores/1
  # PUT /stores/1.json
  def update
    @store = Store.find(params[:id])

    respond_to do |format|
      if @store.update_attributes(params[:store])
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br />
     <%= f.select(:company_id, Company.all.collect{ |g| [g.name, g.id]},  :include_blank => true) %>
  </div>
   <div class="field">
    <%= f.label :store_type_id %><br />
     <%= f.select(:store_type_id, StoreType.all.collect{ |g| [g.name, g.id]},  :include_blank => true) %>
  </div>
  <div class="field">
    <%= f.label :store_number %><br />
    <%= f.text_field :store_number %>
  </div>
  
  <div class="field">
    <%= f.file_field :photo %>
  </div>
  
  <div class="field">
    <%= f.label :address1 %><br />
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br />
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state_id %><br />
     <%= f.select(:state_id, State.all.collect{ |g| [g.name, g.id]},  :include_blank => true) %>
  </div>
  <div class="field">
    <%= f.label :country_id %><br />
     <%= f.select(:country_id, Country.all.collect{ |g| [g.name, g.id]},  :include_blank => true) %>
  </div>
  <div class="field">
    <%= f.label :other_state %><br />
    <%= f.text_field :other_state %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :store_url %><br />
    <%= f.text_field :store_url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :fax %><br />
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<h1>Store List</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Company</th>
    <th>City</th>
    <th>State</th>
    <th>Country</th>
    <th>Phone</th>
    <th>Store url</th>
    <th>Rating</th>
    <th>Fax</th>
    <th>Email</th>
    <th>Store type</th>
    <th>Store number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stores.each do |store| %>
  <tr>
    <td><%= link_to store.name, store %></td>
    <td><%= store.company.name %></td>
    <td><%= store.city %></td>
    <td><%= store.state.name unless store.state_id.nil?%></td>
    <td><%= store.country.name unless store.country.nil?%></td>
    <td><%= store.phone %></td>
    <td><%= store.store_url %></td>
    <td><%= store.rating %></td>
    <td><%= store.fax %></td>
    <td><%= store.email %></td>
    <td><%= store.store_type.name %></td>
    <td><%= store.store_number %></td>
    <td><%= link_to 'Edit', edit_store_path(store) %></td>
    <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<h1><%= @store.name %></h1>

<div class="row">
  

  <div class="span4">
    <ul class="thumbnails">
      <li class="span3">
        <%= image_tag @store.photo.url(:small) %>
      </li>
      <li>
        <strong>Description:</strong><%= simple_format(@store.description) %>
      </li>
    </ul>
  </div>

  <div class="span4">
    <strong>Store Information: </strong>
    <br><%= @store.address1 %>
    <% if !@store.address2.nil? %>
      <%= @store.address2 %>
    <% end %>
    <br><%= @store.city%>, <%= @store.state.state_code unless @store.state.nil? %> 
    <%= @store.zipcode %>, <%= @store.country.name unless @store.country.nil?  %> 
    <br><strong>Phone:</strong> <%= @store.phone %>
    <br>Fax: <%= @store.fax %>
    <br>web: <%= @store.store_url %>
    <br>Email: <%= @store.email %>
    <br>Company:<%= link_to @store.company.name, @store.company %>
    <br>Store number:<%= @store.store_number %>
    <br>Store type:<%= @store.store_type.name %>
  </div>
  
  <div class="span4">
    <b>Friends who have shopped here:</b>
    <% @store.purchases.each do |p| %>
    <br><%= p.user.name unless p.user.nil? %> 
    <% end %>
  </div>

</div>

<br>
<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>