config/routes.rb
Objectspan::Application.routes.draw do
  
  resources :relationship_types

  resources :user_item_relationships

  resources :company_categorizations

  resources :item_categorizations

  resources :categories

  resources :purchase_item_feedbacks

  resources :purchase_feedbacks

  resources :company_contacts

  resources :company_countries

  resources :company_types

  resources :return_duration_types

  resources :exchange_duration_types

  resources :company_return_policies

  resources :company_category_return_policies

  resources :company_items

  resources :mail_in_rebate_statuses

  resources :purchase_item_statuses

  resources :payment_methods

  resources :duration_frequencies

  resources :purchases 
    resources :purchase_items
  

  resources :return_categories

  resources :purchase_statuses

  resources :stores

  resources :states

  resources :countries

  resources :companies

  resources :groups

  resources :visibilities

  resources :store_types

  resources :items do
    collection { post :search, to: 'items#index' }
  end

  resources :makes
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'tags/:tag', to: 'items#index', as: :tag

  match '/auth/:provider/callback', to: 'sessions#create'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

  match '/product', to: 'static_pages#product'

  match '/contact', to: 'static_pages#contact'

  match '/signup', to: 'users#new'

end

app/models/company.rb
class Company < ActiveRecord::Base
	belongs_to :country
	belongs_to :state

	has_many :stores, :dependent => :destroy

	has_many :company_items, :dependent => :destroy
	has_many :items, :through => :company_items

	has_many :company_category_return_policies, :dependent => :destroy
	has_one :company_return_policy, :dependent => :destroy

	has_many :company_categorizations, :dependent => :destroy
	has_many :categories, :through => :company_categorizations
	

	has_attached_file :logo, :styles => { :small => "150x150>", :medium => "300x300>", :thumb => "80x80>" },
							  :url  => "/assets/company/:id/logo/:style/:basename.:extension",
                  			  :path => ":rails_root/public/assets/company/:id/logo/:style/:basename.:extension"

  	
	validates_attachment_size :logo, :less_than => 5.megabytes
	validates_attachment_content_type :logo, :content_type => ['image/jpeg', 'image/png']


	accepts_nested_attributes_for :stores, :company_categorizations, :company_category_return_policies, :allow_destroy => true

  	attr_accessible :logo, :address1, :address2, :city, :country_id, :description, :email, :fax, 
  	:name, :other_state, :phone, :state_id, :url, :zipcode

  	validates :name, :presence => true, uniqueness: { case_sensitive: false }

	default_scope order: :name

end

app/models/company_type.rb
class CompanyType < ActiveRecord::Base
	
  attr_accessible :name
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.file_field :logo %>
  </div>
  
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :fax %><br />
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br />
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br />
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state_id %><br />
     <%= f.select(:state_id, State.all.collect{ |g| [g.name, g.id]},  :include_blank => true) %>
  </div>
  <div class="field">
    <%= f.label :other_state %><br />
    <%= f.text_field :other_state %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :country_id %><br />
     <%= f.select(:country_id, Country.all.collect{ |g| [g.name, g.id]},  :include_blank => true) %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Company List</h1>

<table class="table table-hover">
  <tr>
    <th>&nbsp;</th>
    <th>Name</th>
    <th>Url</th>
    <th>Phone</th>
    <th>Fax</th>
    <th>City</th>
    <th>State</th>
    <th>Zipcode</th>
    <th>Country</th>
    <th>No of stores</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @companies.each do |company| %>
  <tr>
   <td><%= image_tag company.logo.url(:thumb)  %></td> 
    <td><%= company.name %></td>
    <td><%= company.url %></td>
    <td><%= company.phone %></td>
    <td><%= company.fax %></td>
    <td><%= company.city %></td>
    <td>
        <% if !company.state_id.nil? %>
            <%= company.state.name %>
        <% else %>
            <%= company.other_state unless company.other_state.blank? %>
        <% end %>
    </td>
    
    <td><%= company.zipcode %></td>
    <td><%= company.country.name unless company.country_id.nil? %></td>
    <td><%= company.stores.count %></td>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<h1><%= image_tag @company.logo.url(:small) %>&nbsp;<%= @company.name %></h1>

<div class="row" >

<div class="span6">
  <b>Url:</b>
  <a href="<%= @company.url %>" target="_blank"> <%=  @company.url %></a>
</div>

<div class="span6">
  <b>Email:</b>
  <%= @company.email %>
</div>

<div class="span6">
  <b>Phone:</b>
  <%= @company.phone %>
</div>

<div class="span6">
  <b>Fax:</b>
  <%= @company.fax %>
</div>

<div class="span6">
  <b>Address1:</b>
  <%= @company.address1 %>
</div>

<div class="span6">
  <b>Address2:</b>
  <%= @company.address2 %>
</div>

<div class="span6">
  <b>City:</b>
  <%= @company.city %>
</div>

<div class="span6">
  <b>State:</b>
    <% if !@company.state_id.nil? %>
        <%= @company.state.name %>
    <% else %>
        <%= @company.other_state unless @company.other_state.nil? %>
    <% end %>
</div>

<div class="span6">
  <b>Zipcode:</b>
  <%= @company.zipcode %>
</div>

<div class="span6">
  <b>Country:</b>
  <%= @company.country_id %>
</div>

<div class="span12">
  <b>Description:</b>
  <%= @company.description %>
</div>

</div>
<br>


<div class="well">
<h2> Stores </h2>
<%= link_to 'Create New Store', new_store_path %>
<table class="table table-hover">
  <tr>
    <th>SN</th>
    <th>Store Number</th>
    <th>Name</th>
    <th> State</th>
    <th> Country </th>
    <th>Phone</th>
    <th>Store Type </th>
    <th>Purchases</th>
    <th></th>
  </tr>
  <% @company.stores.each_with_index do |s, i| %>
  <tr>
    <td><%= i+1 %></td>
    <td><%= s.store_number %></td>
    <td><%= link_to s.name, s %></td>
    <td> 
      <% if !s.state_id.nil? %>
          <%= s.state.name %>
        <% else %>
          <%= s.other_state unless s.other_state.empty? %>
      <% end %>
    </td>
    <td><%= s.country.name %></td>
    <td><%= s.phone %></td>
    <td><%= s.store_type.name %></td>
    <td><%= s.purchases.count %></td>
    <td><%= link_to "Edit", edit_store_path(s) %> </td>
    <td><%= link_to 'Destroy', s, method: :delete, data: { confirm: 'Are you sure?' } %> </td>
    
  </tr>
  <% end %>
</table>
<%= link_to 'Create New Store', new_store_path %>
</div>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>