config/routes.rb
Objectspan::Application.routes.draw do
  
  resources :relationship_types

  resources :user_item_relationships

  resources :company_categorizations

  resources :item_categorizations

  resources :categories

  resources :purchase_item_feedbacks

  resources :purchase_feedbacks

  resources :company_contacts

  resources :company_countries

  resources :company_types

  resources :return_duration_types

  resources :exchange_duration_types

  resources :company_return_policies

  resources :company_category_return_policies

  resources :company_items

  resources :mail_in_rebate_statuses

  resources :purchase_item_statuses

  resources :payment_methods

  resources :duration_frequencies

  resources :purchases 
    resources :purchase_items
  

  resources :return_categories

  resources :purchase_statuses

  resources :stores

  resources :states

  resources :countries

  resources :companies

  resources :groups

  resources :visibilities

  resources :store_types

  resources :items do
    collection { post :search, to: 'items#index' }
  end

  resources :makes
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'tags/:tag', to: 'items#index', as: :tag

  match '/auth/:provider/callback', to: 'sessions#create'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

  match '/product', to: 'static_pages#product'

  match '/contact', to: 'static_pages#contact'

  match '/signup', to: 'users#new'

end

app/models/return_category.rb
class ReturnCategory < ActiveRecord::Base
	has_many :store_return_category

  	attr_accessible :name

  	validates :name, :presence => true, uniqueness: { case_sensitive: false }
end

app/controllers/return_categories_controller.rb
class ReturnCategoriesController < ApplicationController
  # GET /return_categories
  # GET /return_categories.json
  def index
    @return_categories = ReturnCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @return_categories }
    end
  end

  # GET /return_categories/1
  # GET /return_categories/1.json
  def show
    @return_category = ReturnCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @return_category }
    end
  end

  # GET /return_categories/new
  # GET /return_categories/new.json
  def new
    @return_category = ReturnCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @return_category }
    end
  end

  # GET /return_categories/1/edit
  def edit
    @return_category = ReturnCategory.find(params[:id])
  end

  # POST /return_categories
  # POST /return_categories.json
  def create
    @return_category = ReturnCategory.new(params[:return_category])

    respond_to do |format|
      if @return_category.save
        format.html { redirect_to @return_category, notice: 'Return category was successfully created.' }
        format.json { render json: @return_category, status: :created, location: @return_category }
      else
        format.html { render action: "new" }
        format.json { render json: @return_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /return_categories/1
  # PUT /return_categories/1.json
  def update
    @return_category = ReturnCategory.find(params[:id])

    respond_to do |format|
      if @return_category.update_attributes(params[:return_category])
        format.html { redirect_to @return_category, notice: 'Return category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @return_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /return_categories/1
  # DELETE /return_categories/1.json
  def destroy
    @return_category = ReturnCategory.find(params[:id])
    @return_category.destroy

    respond_to do |format|
      format.html { redirect_to return_categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/return_categories_helper.rb
module ReturnCategoriesHelper
end

app/views/return_categories/_form.html.erb
<%= semantic_form_for(@return_category) do |f| %>

  <%= f.inputs %>
  <%= f.actions %>
<% end %>

app/views/return_categories/edit.html.erb
<h1>Editing return_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @return_category %> |
<%= link_to 'Back', return_categories_path %>

app/views/return_categories/index.html.erb
<h1>Listing return_categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @return_categories.each do |return_category| %>
  <tr>
    <td><%= return_category.name %></td>
    <td><%= link_to 'Show', return_category %></td>
    <td><%= link_to 'Edit', edit_return_category_path(return_category) %></td>
    <td><%= link_to 'Destroy', return_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Return category', new_return_category_path %>

app/views/return_categories/new.html.erb
<h1>New return_category</h1>

<%= render 'form' %>

<%= link_to 'Back', return_categories_path %>

app/views/return_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @return_category.name %>
</p>


<%= link_to 'Edit', edit_return_category_path(@return_category) %> |
<%= link_to 'Back', return_categories_path %>